// Code generated by "stringer -type=Compose"; DO NOT EDIT.

package gfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComposeSrcOver-0]
	_ = x[ComposeCopy-1]
	_ = x[ComposeDest-2]
	_ = x[ComposeClear-3]
	_ = x[ComposeDestOver-4]
	_ = x[ComposeSrcIn-5]
	_ = x[ComposeDestIn-6]
	_ = x[ComposeSrcOut-7]
	_ = x[ComposeDestOut-8]
	_ = x[ComposeSrcAtop-9]
	_ = x[ComposeDestAtop-10]
	_ = x[ComposeXor-11]
	_ = x[ComposePlus-12]
	_ = x[ComposePlusLighter-13]
}

const _Compose_name = "ComposeSrcOverComposeCopyComposeDestComposeClearComposeDestOverComposeSrcInComposeDestInComposeSrcOutComposeDestOutComposeSrcAtopComposeDestAtopComposeXorComposePlusComposePlusLighter"

var _Compose_index = [...]uint8{0, 14, 25, 36, 48, 63, 75, 88, 101, 115, 129, 144, 154, 165, 183}

func (i Compose) String() string {
	if i >= Compose(len(_Compose_index)-1) {
		return "Compose(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Compose_name[_Compose_index[i]:_Compose_index[i+1]]
}
