// Code generated by "stringer -type=Mix"; DO NOT EDIT.

package gfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MixNormal-0]
	_ = x[MixMultiply-1]
	_ = x[MixScreen-2]
	_ = x[MixOverlay-3]
	_ = x[MixDarken-4]
	_ = x[MixLighten-5]
	_ = x[MixColorDodge-6]
	_ = x[MixColorBurn-7]
	_ = x[MixHardLight-8]
	_ = x[MixSoftLight-9]
	_ = x[MixDifference-10]
	_ = x[MixExclusion-11]
	_ = x[MixHue-12]
	_ = x[MixSaturation-13]
	_ = x[MixColor-14]
	_ = x[MixLuminosity-15]
	_ = x[MixClip-128]
}

const (
	_Mix_name_0 = "MixNormalMixMultiplyMixScreenMixOverlayMixDarkenMixLightenMixColorDodgeMixColorBurnMixHardLightMixSoftLightMixDifferenceMixExclusionMixHueMixSaturationMixColorMixLuminosity"
	_Mix_name_1 = "MixClip"
)

var (
	_Mix_index_0 = [...]uint8{0, 9, 20, 29, 39, 48, 58, 71, 83, 95, 107, 120, 132, 138, 151, 159, 172}
)

func (i Mix) String() string {
	switch {
	case i <= 15:
		return _Mix_name_0[_Mix_index_0[i]:_Mix_index_0[i+1]]
	case i == 128:
		return _Mix_name_1
	default:
		return "Mix(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
